apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: sample-pipline
spec:
  resources:
    - name: app
      type: git
    - name: image
      type: image
  tasks:
  - name: unit-test
    taskRef:
      name: go-test
    params:
      - name: pathToDockerFile
        value: /workspace/app/Dockerfile
      - name: pathToContext
        value: /workspace/app
    resources:
      inputs:
      - name: app
        resource: app
  - name: build-push-image
    runAfter: [unit-test]
    taskRef:
      name: build-image
    params:
      - name: pathToDockerFile
        value: /workspace/app/Dockerfile
      - name: pathToContext
        value: /workspace/app
    resources:
      inputs:
      - name: app
        resource: app
      outputs:
      - name: builtImage
        resource: image
  - name: deploy
    runAfter: [build-push-image]
    taskRef:
      name: deploy-kubectl
    params:
      - name: path
        value: /workspace/app/manifest.yaml
    resources:
      inputs:
      - name: app
        resource: app

