apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: tekton-sample-resource-image
spec:
  type: image
  params:
    - name: url
      value: gcr.io/my-first-project-236315/tekton-sample-image