apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: tekton-sample-resource-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/tommy-sho/tekton-sample.git # modify to your git repository