apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-kubectl
spec:
  inputs:
    resources:
      - name: app
        type: git
    params:
      - name: path
        description: Path to the manifest to apply
  steps:
    - name: run-kubectl
      image: lachlanevenson/k8s-kubectl
      command: ['kubectl']
      args:
        - 'apply'
        - '-f'
        - '${inputs.params.path}'